field: cbc7d1f8-d1e1-4e73-900f-4446c434467a # Flexible Content Test
fieldLayouts:
  74046e26-83b1-4c05-b5b7-a0401f688af5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d91ee4fe-03e7-4894-b1bd-5748a2757cea # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd7b40ba-dd22-460d-868b-3e7ba4a6c1bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c3d9ee1-fa50-4a1a-b014-fe2cc2a8e715 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38fbefe8-e3e6-4062-a716-98763ef8a8f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba2732b7-3708-462e-9794-110caebda7c4
        userCondition: null
fields:
  5c3d9ee1-fa50-4a1a-b014-fe2cc2a8e715: # Copy
    columnSuffix: xjzmrlcs
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d91ee4fe-03e7-4894-b1bd-5748a2757cea: # Headline
    columnSuffix: mwdauzdb
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: block2
name: Block2
sortOrder: 2
