field: 8ae99c4a-f34c-490d-9e3a-1ed3bb2a96b2 # Flexible Content
fieldLayouts:
  dcc21363-9a6e-454f-a476-0d0d0ca70557:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42caa027-4021-4d69-9c12-60df8e7b73c9 # Block2 Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782bb1f2-c028-4c1e-b5d8-ff8c1e8fcf67
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 628b25c7-5a2a-4b1d-bc74-50f61c6c802e # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67f973aa-85db-4aad-8d83-d0711aba9d10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9b8dce3a-a14f-483f-bd1d-35d12f0d2690
        userCondition: null
fields:
  42caa027-4021-4d69-9c12-60df8e7b73c9: # Block2 Title
    columnSuffix: jhdvhcns
    contentColumnType: text
    fieldGroup: null
    handle: block2Title
    instructions: null
    name: 'Block2 Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  628b25c7-5a2a-4b1d-bc74-50f61c6c802e: # Copy
    columnSuffix: qbgrznex
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: block2
name: Block2
sortOrder: 2
