field: cbc7d1f8-d1e1-4e73-900f-4446c434467a # Flexible Content Test
fieldLayouts:
  20b016d3-a119-48cb-97eb-20d21b58471c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a96d7157-2fee-40f5-be22-4393da46eed5 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a8e9fa1-4feb-454a-8073-ccd38ef8b783
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bfdab4cd-2c3b-47cd-90e0-030896b4ccbb # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e665919-4aae-4fa9-bf2c-f1b3c590c156
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f2fb05b3-b5d2-4e5f-994d-7e593ffcf527
        userCondition: null
fields:
  a96d7157-2fee-40f5-be22-4393da46eed5: # Headline
    columnSuffix: tmlvsryk
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bfdab4cd-2c3b-47cd-90e0-030896b4ccbb: # Copy
    columnSuffix: zdunwetq
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: block1
name: Block1
sortOrder: 1
