field: bb17fd16-c37c-4754-bb83-b9f6f6de89fc # Nav Links
fieldLayouts:
  81dcc0f1-85a5-4d1b-9e37-5dc413f21535:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 15aecb61-314d-4c70-adcd-074b17d648ce # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5525f891-2e5e-4ba7-9580-54e0ebe98b7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 021d4b47-bc7f-4d3f-857a-637e21ee42f4 # Link Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6901738-77eb-4bab-9a8d-de65198ecc7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e97c6f6c-ab3e-459c-9300-076eb62cbe7f
        userCondition: null
fields:
  15aecb61-314d-4c70-adcd-074b17d648ce: # Link Text
    columnSuffix: dmlwsaio
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  021d4b47-bc7f-4d3f-857a-637e21ee42f4: # Link Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: null
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Select an Entry'
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: link
name: Link
sortOrder: 1
