field: a2831532-0d6d-4318-a53c-c56c59d0a682 # Hover Modules Container
fieldLayouts:
  9f4d4776-a0f4-4811-89e0-7b179ee027a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53912735-f1ba-46a4-af5f-a48fc6f58d85 # Module Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63bdb784-8953-41bc-aa50-a3a63d005611
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0216524b-0bbe-4ca3-b03b-3acb4c52ce08
        userCondition: null
fields:
  53912735-f1ba-46a4-af5f-a48fc6f58d85: # Module Title
    columnSuffix: cgnzlacb
    contentColumnType: text
    fieldGroup: null
    handle: moduleTitle
    instructions: null
    name: 'Module Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: module
name: Module
sortOrder: 1
