field: 04e5afe5-0399-4235-94a2-8b74f4faeb8a # SliderContainer
fieldLayouts:
  dafbcd58-f887-48c2-ab14-5b843287eef6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c9139736-05b1-4b41-90b2-71d48aac36c5 # Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92de8d37-197f-465e-8045-a9e0dd131a30
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d24d8cb-4747-4bc5-9b16-c24cf6f8d09a # Slide Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b100149-624f-4524-ade4-96879138e048
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47ace591-f861-49e0-ab97-1504aa7c6079
        userCondition: null
fields:
  7d24d8cb-4747-4bc5-9b16-c24cf6f8d09a: # Slide Copy
    columnSuffix: zjucrjcr
    contentColumnType: text
    fieldGroup: null
    handle: slideCopy
    instructions: null
    name: 'Slide Copy'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c9139736-05b1-4b41-90b2-71d48aac36c5: # Slide Title
    columnSuffix: ufaihgyz
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: 'Slide Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: slide
name: Slide
sortOrder: 1
