fieldLayouts:
  cb2bc273-c6a3-488d-8912-64315810e37b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea9dcff4-9303-4f1c-b397-8f9e54547091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea633514-acd9-4e88-a61a-cd5981e869f2 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 245066b2-2dfb-4da6-bc98-de95e950f3d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbc7d1f8-d1e1-4e73-900f-4446c434467a # Flexible Content Test
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d476f51-b952-4f9f-a979-ec63af66503a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 74bae685-e077-4384-862b-d3d1ae6eaf0c
        userCondition: null
handle: generalPages
hasTitleField: true
name: 'General Pages'
section: 20d491f0-75e2-4083-a3a9-c2365c34958a # General Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
