fieldLayouts:
  bede0e2a-eb4a-4b92-b927-f4d65d2a43e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 581665f5-b39a-4e5c-bdbc-ed16d26cf7d7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b98a8938-1da7-4514-9727-9dfe3ff79f0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01e3bca3-1c13-45b2-b071-7542eca83665 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88673388-449e-4a63-8fd4-d7f26ede48ce
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41e95b13-e94d-4042-9cdd-f8ba4568397c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ae99c4a-f34c-490d-9e3a-1ed3bb2a96b2 # Flexible Content Home Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa5f176d-23c8-4007-b594-f4edc6f39242
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81b15e17-b6ce-4808-8973-e84babe62107
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d2bd35fe-f728-44f0-8dc6-f489c7d0dfac # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
