fieldLayouts:
  bede0e2a-eb4a-4b92-b927-f4d65d2a43e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 581665f5-b39a-4e5c-bdbc-ed16d26cf7d7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b98a8938-1da7-4514-9727-9dfe3ff79f0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01e3bca3-1c13-45b2-b071-7542eca83665 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88673388-449e-4a63-8fd4-d7f26ede48ce
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41e95b13-e94d-4042-9cdd-f8ba4568397c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ae99c4a-f34c-490d-9e3a-1ed3bb2a96b2 # Flexible Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa5f176d-23c8-4007-b594-f4edc6f39242
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81b15e17-b6ce-4808-8973-e84babe62107
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 92391549-451d-48f6-bfc8-a69f14bc11ce # Home Page Left Right Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac0faae4-2a85-40f1-9296-93431759e507
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 649b71b8-1ee7-4215-9706-cd89e1c7847d # Home Page Left Right Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3815c879-f582-438e-8ac7-911cbced0b7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c81d90a3-af61-4fcd-9b0e-9e386abd15a0 # Home Page Left Right Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78c3d1e2-41ae-45ee-9422-d88844b761c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d67225f0-12b0-4fa7-b7fe-f166a2184a96 # Home Page Left Right Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e36072c8-b22b-427f-8763-c25a03d0acf8
            userCondition: null
            warning: null
            width: 100
        name: 'Left Right'
        uid: b2ce1f6e-4a05-4c5f-bc47-83b38dafb516
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d2bd35fe-f728-44f0-8dc6-f489c7d0dfac # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
