fieldLayouts:
  f4a19b36-6ca0-477d-8d43-f2664f89d3cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a5ca40c0-ec50-4c16-ba53-115dc9674d27
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ab5692d0-f40e-4b52-b6d0-0e5b1af367cf
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: hardDisk
transformSubpath: ''
