columnSuffix: null
contentColumnType: string
fieldGroup: cb7c5995-bc64-48d8-82df-be48dfe24f54 # Common
handle: flexibleContentHomePage
instructions: null
name: 'Flexible Content Home Page'
searchable: false
settings:
  contentTable: '{{%matrixcontent_flexiblecontenthomepage}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
