columnSuffix: null
contentColumnType: string
fieldGroup: 7df69a92-4f52-4458-a156-40f95c71286c # Home Page
handle: homePageLeftRightImage
instructions: null
name: 'Home Page Left Right Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:d3699ba7-b37b-472a-97b2-57de705f93ce' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:d3699ba7-b37b-472a-97b2-57de705f93ce' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:d3699ba7-b37b-472a-97b2-57de705f93ce' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
