columnSuffix: lptocjcm
contentColumnType: text
fieldGroup: 7df69a92-4f52-4458-a156-40f95c71286c # Home Page
handle: homePageLeftRightCopy
instructions: null
name: 'Home Page Left Right Copy'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
