changedFieldIndicator: 1352711170
field: 16b04d9a-8458-47f1-89a1-6adb8d0e1d24 # SliderTable
fieldLayouts:
  510b895b-182e-4547-800c-df62bccad9d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aeaed4bf-d719-4ca8-b82b-191817675019 # Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83c8747b-3424-403e-af46-aab52b3a9fe5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 283c9704-d69c-4196-9e6e-d3037d5da81a # Slider Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c24d40ef-acad-41aa-8cde-72011142196e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04e5afe5-0399-4235-94a2-8b74f4faeb8a # SliderContainer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8ec4255-2c3f-4af4-afeb-9515edf0cf1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00a2b09e-3032-40e1-a1ea-f5bf48ff18d0
        userCondition: null
fields:
  04e5afe5-0399-4235-94a2-8b74f4faeb8a: # SliderContainer
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sliderContainer
    instructions: null
    name: SliderContainer
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_slidercontainer}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  283c9704-d69c-4196-9e6e-d3037d5da81a: # Slider Copy
    columnSuffix: hiahggze
    contentColumnType: text
    fieldGroup: null
    handle: sliderCopy
    instructions: null
    name: 'Slider Copy'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aeaed4bf-d719-4ca8-b82b-191817675019: # Slider Title
    columnSuffix: gcpbzsbd
    contentColumnType: text
    fieldGroup: null
    handle: sliderTitle
    instructions: null
    name: 'Slider Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
