fieldLayouts:
  717f854c-f9f4-4178-98ed-057ea260fcfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ea633514-acd9-4e88-a61a-cd5981e869f2 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19983e50-427f-4416-9948-842aa6ec2e50
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 294dc4d4-2803-4f73-b84b-8499bdcedeca
        userCondition: null
handle: footer
name: Footer
sortOrder: 4
