defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  f58ae7aa-9b55-4ed4-8f80-5cc7196791c1: # Test
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
